-- Initialize schema for retail dataset
CREATE TABLE IF NOT EXISTS customers (
  CUSTOMER_ID INT PRIMARY KEY,
  FIRST_NAME VARCHAR(100),
  LAST_NAME VARCHAR(100),
  EMAIL VARCHAR(255),
  PHONE VARCHAR(50),
  ADDRESS VARCHAR(255),
  CITY VARCHAR(100),
  STATE VARCHAR(10),
  POSTAL_CODE VARCHAR(20),
  COUNTRY VARCHAR(50),
  CREATED_AT DATETIME
);

CREATE TABLE IF NOT EXISTS products (
  PRODUCT_ID INT PRIMARY KEY,
  PRODUCT_NAME VARCHAR(255),
  CATEGORY VARCHAR(50),
  PRICE DECIMAL(10,2),
  COST DECIMAL(10,2),
  ACTIVE BOOLEAN,
  CREATED_AT DATETIME
);

CREATE TABLE IF NOT EXISTS orders (
  ORDER_ID INT PRIMARY KEY,
  CUSTOMER_ID INT,
  ORDER_DATE DATETIME,
  STATUS VARCHAR(20),
  ORDER_TOTAL DECIMAL(12,2),
  CONSTRAINT fk_orders_customer FOREIGN KEY (CUSTOMER_ID) REFERENCES customers(CUSTOMER_ID)
);

CREATE TABLE IF NOT EXISTS order_items (
  ORDER_ITEM_ID INT PRIMARY KEY,
  ORDER_ID INT,
  PRODUCT_ID INT,
  QUANTITY INT,
  UNIT_PRICE DECIMAL(10,2),
  EXTENDED_PRICE DECIMAL(12,2),
  CONSTRAINT fk_oi_order FOREIGN KEY (ORDER_ID) REFERENCES orders(ORDER_ID),
  CONSTRAINT fk_oi_product FOREIGN KEY (PRODUCT_ID) REFERENCES products(PRODUCT_ID)
);

CREATE INDEX IF NOT EXISTS idx_orders_customer ON orders(CUSTOMER_ID);
CREATE INDEX IF NOT EXISTS idx_oi_order ON order_items(ORDER_ID);

