USE DATABASE DM_DEMO;
USE SCHEMA RAW;

CREATE TABLE IF NOT EXISTS CUSTOMERS (
	CUSTOMER_ID NUMBER NOT NULL,
	FIRST_NAME STRING,
	LAST_NAME STRING,
	EMAIL STRING,
	PHONE STRING,
	ADDRESS STRING,
	CITY STRING,
	STATE STRING,
	POSTAL_CODE STRING,
	COUNTRY STRING,
	CREATED_AT TIMESTAMP_NTZ,
	PRIMARY KEY (CUSTOMER_ID)
);

CREATE TABLE IF NOT EXISTS PRODUCTS (
	PRODUCT_ID NUMBER NOT NULL,
	PRODUCT_NAME STRING,
	CATEGORY STRING,
	PRICE NUMBER(10,2),
	COST NUMBER(10,2),
	ACTIVE BOOLEAN,
	CREATED_AT TIMESTAMP_NTZ,
	PRIMARY KEY (PRODUCT_ID)
);

CREATE TABLE IF NOT EXISTS ORDERS (
	ORDER_ID NUMBER NOT NULL,
	CUSTOMER_ID NUMBER NOT NULL,
	ORDER_DATE TIMESTAMP_NTZ,
	STATUS STRING,
	ORDER_TOTAL NUMBER(12,2),
	PRIMARY KEY (ORDER_ID)
);

CREATE TABLE IF NOT EXISTS ORDER_ITEMS (
	ORDER_ITEM_ID NUMBER NOT NULL,
	ORDER_ID NUMBER NOT NULL,
	PRODUCT_ID NUMBER NOT NULL,
	QUANTITY NUMBER(10,0),
	UNIT_PRICE NUMBER(10,2),
	EXTENDED_PRICE NUMBER(12,2),
	PRIMARY KEY (ORDER_ITEM_ID)
); 