USE DATABASE DM_DEMO;
CREATE SCHEMA IF NOT EXISTS CORE;
USE SCHEMA CORE;

CREATE OR REPLACE VIEW DIM_CUSTOMER AS
SELECT
	c.CUSTOMER_ID,
	c.FIRST_NAME,
	c.LAST_NAME,
	c.EMAIL,
	c.PHONE,
	c.CITY,
	c.STATE,
	c.COUNTRY,
	c.CREATED_AT AS CUSTOMER_CREATED_AT
FROM RAW.CUSTOMERS c;

CREATE OR REPLACE VIEW DIM_PRODUCT AS
SELECT
	p.PRODUCT_ID,
	p.PRODUCT_NAME,
	p.CATEGORY,
	p.PRICE,
	p.COST,
	p.ACTIVE,
	p.CREATED_AT AS PRODUCT_CREATED_AT
FROM RAW.PRODUCTS p;

CREATE OR REPLACE VIEW FACT_ORDER AS
SELECT
	oi.ORDER_ITEM_ID,
	o.ORDER_ID,
	o.CUSTOMER_ID,
	oi.PRODUCT_ID,
	o.ORDER_DATE,
	CASE WHEN o.STATUS = 'CANCELLED' THEN 0 ELSE oi.QUANTITY END AS QUANTITY,
	CASE WHEN o.STATUS = 'CANCELLED' THEN 0 ELSE oi.EXTENDED_PRICE END AS SALES_AMOUNT
FROM RAW.ORDER_ITEMS oi
JOIN RAW.ORDERS o ON o.ORDER_ID = oi.ORDER_ID;

-- Common aggregates
CREATE OR REPLACE VIEW SALES_BY_DAY AS
SELECT
	DATE_TRUNC('day', ORDER_DATE) AS ORDER_DAY,
	SUM(SALES_AMOUNT) AS TOTAL_SALES,
	SUM(QUANTITY) AS TOTAL_QUANTITY
FROM FACT_ORDER
GROUP BY 1; 